# Generated by Django 4.0 on 2022-09-30 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_post_title_alter_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('publish_date', models.DateField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_details', to='api.book')),
            ],
        ),
    ]
